services:
  db:
    image: postgres:16
    container_name: seas_db
    environment:
      POSTGRES_DB: seas
      POSTGRES_USER: seas_user
      POSTGRES_PASSWORD: seas_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
